### ISSUE TITLE
Vocabulary Image URL improvement 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#108]
Make it working also with relative URL

![2020_08_03_12_54_57_Administration_Climate_and_Land_Hub.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/263d8247-6e90-4c82-9fb0-2a81e75be081)

**Comment by etj** [comment]
Quick change: the input type is now "text".
We should check for URL validity.
