### ISSUE TITLE
Small CSS changes

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#114]
Small CSS changes are required:

**Breadcrumbs**

- [ ] Update Font-size 14px

**Dataset view**

- [ ] Update CSS on rating starts
   - Update star border color to be consistent with half star (#bdc3c7)
   - Update color for not given rating (#bdc4c7)
   - Increase stars font size 20 px

**Comment by abulojoshua1** [comment]
[Here](https://github.com/geosolutions-it/ckanext-rating/pull/2) is a PR in ckanext-ratings GS fork repo with changes to the ratings starts
