### ISSUE TITLE
Investigate CKAN Instabilities

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/ckanext-faoclh#117]
FAO installation is freezing sometimes, we need to investigate further.

**Comment by etj** [comment]
CKAN by default does not clean up the session cache files (see also [this issue](https://github.com/ckan/ckan/issues/5294)).  
Cache files are stored in a subdir of the `/tmp` direcotory; If your server is not rebooted every few days, the session files may fill up
the inode space, and the system may become unstable.
