### ISSUE TITLE
New attributes for resources

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#119]
New attribute for resources “Type of resource” need to be added in the resource schema, each resource will have this attribute.

We need to move the Type of resource field from the dataset schema to the resource schema. We don't need to fill the related attribute field in resource: the CLH team will take care of this.

**Comment by tdipisa** [comment]
Trying to create a new resource in a dataset, we have the following error

![image](https://user-images.githubusercontent.com/1280027/95735895-c1690100-0c85-11eb-8979-e25282a358a9.png)

**How to reproduce:**

I tried to create a new resource on this Test dataset:
http://faoclh.geo-solutions.it/dataset/test-dataset

Below a GIF to reproduce the error:

![clh_bug](https://user-images.githubusercontent.com/1280027/95736314-58ce5400-0c86-11eb-9648-c3f0e9fd7d5a.gif)

**Comment by etj** [comment]
It was caused by a bad restart of solr.
