### ISSUE TITLE
Rating and Users feedbacks

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#23]
For each dataset the users should have the possibility to provide their feedbacks through a Like mechanism, then a rating system should show the ""openness score"" for each dataset  (only for authenticated users).
Also user comments are required for the dataset page (only for authenticated users). Comments must be visible only to administrators

**Comment by tdipisa** [comment]
As reported by the client only anonymous accesses are axpected for the CKAN portal for now, therefore the "like" functionality cannot be implemented. Since the Rating is calculated by CKAN, it is not needed too for now.

**Comment by tdipisa** [comment]
Issue un-blocked: we can have authenticated user.

### RATINGS
**TODO**

### USER COMMENTS

- [ ] [Disqus extension](https://github.com/ckan/ckanext-disqus) works, but comments are stored through disqus services, which requires a monthly/yearly fee

- [X] [ytp works](https://github.com/vrk-kpa/ckanext-ytp-comments), but it does not work as requested

It may be customized in order to only display comments written by the current user.

We will use **ytp** by fixing it in a fork

**Comment by abulojoshua1** [comment]
@tdipisa, I am not able to fork [ckanext-rating](https://github.com/6aika/ckanext-rating) into [geosolutions-it](https://github.com/geosolutions-it) Github. My fork went straight to my GitHub. Could it be that I am missing some permissions?

**Comment by tdipisa** [comment]
@abulojoshua1 the forked repo here: https://github.com/geosolutions-it/ckanext-rating
