### ISSUE TITLE
Management of custom vocabularies from CKAN UI

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#28]
FAO CLH needs the possibility to manage custom vocabularies (Type of Resource, Kind of Activity and Geographic Focus) from the CKAN’s admin UI: this means the possibility to add/rename (not remove) vocabulary entries. 

The custom vocabularies has already been implemented in issue #3

A new custom admin page must be created for CKAN in this extension and it must reachable from the admin toolbar where a new icon will be included (that icon will be visible only to admins)

An "how to" documentation for this admin UI must be provided in a specific section of the [README file](https://github.com/geosolutions-it/ckanext-faoclh/blob/master/README.md)

**Comment by tdipisa** [comment]
@abulojoshua1 remember to provide a simple mockup before starting the development.

**Comment by abulojoshua1** [comment]
> @abulojoshua1 remember to provide a simple mockup before starting the development.

@tdipisa, here are links to, and attached are screenshots of the mockups I created for this issue:
[Display of vocabularies](https://www.figma.com/file/nCeKjrTwQZPpgLMFwFe7F6/List-Vocabs?node-id=0%3A1)

<img width="867" alt="Screenshot 2020-04-14 at 15 58 28" src="https://user-images.githubusercontent.com/29429135/79227852-355a5600-7e69-11ea-9a00-ff77808c2ec8.png">

[Create/Update Vocabularies](https://www.figma.com/file/nCeKjrTwQZPpgLMFwFe7F6/List-Vocabs?node-id=1%3A2)

<img width="787" alt="Screenshot 2020-04-14 at 15 58 12" src="https://user-images.githubusercontent.com/29429135/79227837-312e3880-7e69-11ea-89e0-0982ebb4777a.png">

Kindly review and provide feedback :)

**Comment by tdipisa** [comment]
@abulojoshua1 
some feedbacks below

1. The mockup in general looks good but I would like to have this section available in the **ckan-admin** page, see the image below

![image](https://user-images.githubusercontent.com/1280027/79234113-15776200-7e6a-11ea-9d82-6ab3c5200291.png)

What is the **Edit Settings** button for? 

2. You have to consider the possibility to specify labels for different languages that we have to support (Italian, English, French, Spanish, Arabic, Russian, Chinese). We have the issue #24 for this but probably it would be better to consider something here according also to the existing support provided by @etj (probably a multilingual support for client's vocabularies already exists in the current implementation provided by @etj and we don't need to use the ckanext-multilang extension here).

I have in mind more **Label** fields, one for each language we have to support.

**Question:** when does this screen appear (screenshot 2)? Probably a cancel button might be useful too.

**Comment by abulojoshua1** [comment]
@tdipisa, the edit settings button is just a representation of the button found in FAO CKAN [dashboard](http://faoclh.geo-solutions.it/dashboard/). But according to your feedback, It looks like I will have to transfer the `My Custom Vocabularies` tab to the admin page which already gets rid of the `Edit Settings` button mentioned above.

**Comment by abulojoshua1** [comment]
@tdipisa, [screenshot 2](https://user-images.githubusercontent.com/29429135/79227837-312e3880-7e69-11ea-89e0-0982ebb4777a.png) appears when a user clicks the `Add geographic focus` button on the top left corner of [screenshot 1](https://user-images.githubusercontent.com/29429135/79227852-355a5600-7e69-11ea-9a00-ff77808c2ec8.png).

**Comment by etj** [comment]
There's no support for the multilang in the exisitng code. 
The only support was in the format of the input json file.

**Comment by tdipisa** [comment]
@etj 
>There's no support for the multilang in the exisitng code.
The only support was in the format of the input json file.

ok, therefore we can do that directly within #24 I think. I'm just wondering if, considering your existing implementation, we have to use ckanext-multilang for this or not.

@abulojoshua1 
>@tdipisa, the edit settings button is just a representation of the button found in FAO CKAN dashboard. But according to your feedback, It looks like I will have to transfer the My Custom Vocabularies tab to the admin page which already gets rid of the Edit Settings button mentioned above.

yes, you are right.

>@tdipisa, screenshot 2 appears when a user clicks the Add geographic focus button on the top left corner of screenshot 1.

Yes, I understood that but I think we should have something like the following:

![ckan-admin](https://user-images.githubusercontent.com/1280027/79247527-f1704c80-7e7a-11ea-8624-33e913bc62b6.jpg)

If the form has been modified and there are unsaved changes, as soon the admin clicks on Cancel button or switch to another tab/Ckan's section a confirmation dialog should appear: if the admin confirms, the changes are lost.

**Comment by tdipisa** [comment]
@abulojoshua1 

please proceed on implementing the admin UI according to the above comments.
Within this issue you don't have to provide the multilingual support for labels, you will do that with #24, that means that for the moment we can have the Label field disabled and manage only the Name (that correspond to the vocabulary item key, see [here](https://github.com/geosolutions-it/ckanext-faoclh/blob/master/init/vocab/fao_activity_type.json#L5) for an example).
