### ISSUE TITLE
CLH custom Schema - List of Values

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#3]
Currently the list of values are hardcoded in the client's extension mock (sse #2). 
This values need to be managed in JSON format via script in ordert to:

- Modify existing values
- Delete existing values
- Create new values

**Comment by etj** [comment]
- [ ] change schema validators to accept only values from the thesaurus
- [ ] editing form should be a dropdown using thesaurus values
- [ ] paster command to load / update a thesaurus
- [ ] create sample thesaurus file
