### ISSUE TITLE
VM preparation for local developments

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#31]
A copy of the VM available [here](http://faoclh.geo-solutions.it/) should be provided so CKAN developers can download and use it locally.
Also a simple guide (only the essentials information) is needed here to explain the steps to install and start the VM locally with VMWare player.

**Comment by randomorder** [comment]
@tdipisa
The VM is can be downloaded [here](https://www.dropbox.com/work/Apps/Demo%20Backups/FAO?preview=FAO-CLH.bak.tar.gz)

**Comment by randomorder** [comment]
Sorry, what is the project code? C013-FAO-2019-CL-HUB?
