### ISSUE TITLE
Export of Dataset

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#32]
The structure of the export should include only the fields below:

* title Dataset
* Topics Dataset (comma delimited)
* Tags Dataset (comma delimited)
* ""Kind of Activity"" Dataset
* ""Type of Resource"" Dataset
* title Resource
* format Resource
* ""Year of release"" Resource

​It is enough for the client to have this functionality available inside the same admin page used to manage vocabularies (see issue #28).

### Other useful information

The client required Excel format but also **CSV** can be used, we need to consider the possibility where CKAN has several datasets and in this situation it will take a lot of time to generate the export file.

**Solution:**
We can create a cron based script to generate a csv dump using [ckanapi-exporter](https://github.com/ckan/ckanapi-exporter). The updated file will be accessible for download at a given URL.

Within this issue we need to include and configure the mentioned extension above in the FAO CLH CKAN installation making it working properly, then the README file must be updated by reporting the installation  and configuration procedure: we can consider to provide a new section in the README file where all additional extensions ade documented in the same way.

**Comment by abulojoshua1** [comment]
@tdipisa, I have a few questions regarding this ticket:
- After how long, will the cron job run?
- Should it create a CKAN plugin command to create CSV files for all datasets?
Just for clarity:
- Should I add a create a download route that displays all CSV files ready for download
- Should I create a download route for CSV files in ckanext-faoclh?

**Comment by tdipisa** [comment]
@abulojoshua1 

>After how long, will the cron job run?
@etj mentioned a cron based script for this from his investigation, but I think that it is not so clear to me. I don't know precisely how the ckanapi-exporter works, but what we need here is the possibility to run an export process only on demand from the Ckan admin UI

>Should I create a CKAN plugin command to create CSV files for all datasets?
Yes, probably it could be a good solution, but I repeat: the export process must be activated from the CKAN admin UI and not automatically after a certain period.

>Should I add a create a download route that displays all CSV files ready for download
I would say yes, but the CSV output shouldn't be more than one file I think, let's talk with @etj to clarify this point 

>Should I create a download route for CSV files in ckanext-faoclh?
Yes, I presume. I think that probably a meeting with @etj is needed to better clarify this issue.

**Comment by etj** [comment]
- There will be a button to export the dataset list.
- Once pressed, some new internal logic will run the export, using ckanapi-exporter as a library
- A new file will be created in a configured directory, with name something like `CKAN-EXPORT-<timestamp>.exporting`
- When the export has completed, the file will be renamed as `CKAN-EXPORT-<timestamp>.CSV`
- The export direcotry will be visibile, so that the users can download the exported file version they need
- The fact of having one export file for every export request will prevent the overwriting of files in case the export takes really long and a second export request is issues before the previous has completed
- A cron job will remove the older files
- The export procedure should run asynch wrt the request, in order to prevent that if the client disconnects the process will be killed (needed?)
- In order to simplify things our side, the user will not be notified about the export completion: the user can check it by himself by looking at the filename (.exporting or .csv)

**Comment by abulojoshua1** [comment]
@etj, @tdipisa, The pictorial (mockups) below shows the steps I intend to follow to enable the export of datasets to CSV:

- A user navigates to the "export dataset" admin tab and clicks a button (generate export CSV file) to generate the export CSV file asynchronously.

A process is then run to generate the report asynchronously, the CSV file is created in a directory, it's (the CSV file) path, name, creation status together with session-id which triggered dataset generation is store in a database table.

<img width="1173" alt="Screenshot 2020-04-28 at 17 16 34" src="https://user-images.githubusercontent.com/29429135/80504524-e5f14b00-897b-11ea-8987-5c0d8667c1bb.png">

A screen similar to the one below will be on display once the user click the button to generate datasets

<img width="1170" alt="Screenshot 2020-04-28 at 18 35 33" src="https://user-images.githubusercontent.com/29429135/80507099-1dadc200-897f-11ea-8b85-2f6c6a077459.png">


- The user then waits for the dataset to be generated before clicking a download link provided.

An ajax request is then sent periodically, hitting the database to check if the status of the CSV file being generated is done. This query will base on the current user's session-id to filter for values in the database table. when the dataset creation is complete, a download link will be provided to the user.
<img width="1174" alt="Screenshot 2020-04-28 at 17 19 55" src="https://user-images.githubusercontent.com/29429135/80504553-ec7fc280-897b-11ea-823b-b063358a179b.png">

- The user clicks the link and a CSV file download starts

**Comment by tdipisa** [comment]
As reported by @abulojoshua1 this task will be implemented with:
https://docs.ckan.org/en/2.8/maintaining/background-tasks.html

**Comment by abulojoshua1** [comment]
@tdipisa, @etj, as discussed in the chats, looks like I missed using the dataset schema "year of release" and instead went for the year from the dataset's date of entry (which is definitely wrong) when generating the export CSV file. According to issue https://github.com/geosolutions-it/ckanext-faoclh/issues/57, custom dataset schema "year of release" should be removed. Therefore, should use resource year of release in the export CSV file or instead totally remove the "year of release" column from the export CSV?

**Comment by tdipisa** [comment]
@etj @abulojoshua1 as reported in the description the **year of release** for resources must be present in the exported CSV, therefore we only have to remove the **year of resources** for datasets if currently exported.
