### ISSUE TITLE
Missing custom facets in organization, topics and home pages

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/ckanext-faoclh#37]
Currently custom facets are not visible or accessible via helpers in the organization, topics and home pages.

**Comment by etj** [comment]
Error is in CKAN, fixed here
https://github.com/ckan/ckan/commit/64af68cb8eb77658b0a56f64dde2a494f8c2aed1#diff-379752379d1d722bcb76beff6e0ebef8

From version 2.8.4 the issue is solved.
