### ISSUE TITLE
Facets Sorting Review

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#49]
Investigate the possibility to change the order to CKAN facets in dataset search page as follow:

  1) Topics
  2) Kind of Activity
  3) Type of Resource
  4) Tags
  5) Geographic Focus
  6) Organizations
  7) Formats

**Comment by abulojoshua1** [comment]
@tdipisa, should I raise a PR for this or end at investigating?

**Comment by tdipisa** [comment]
@abulojoshua1 if you have a valid solution for this please proceed on implementing it. I saw you have already provided an estimate, so go ahead.
