### ISSUE TITLE
Collapsing Facets in Dataset Page

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#50]
Investigate on the possibility to collapse facets on dataset search page. All facets should be collapsed by default when the user opens the [dataset search page](http://faoclh.geo-solutions.it/dataset).

Collapsed:
![2020_05_21_09_37_55_Datasets_CKAN.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/25d34dba-8797-4d8f-ad13-a72a04310fb6)

Expanded:
![2020_05_21_09_34_48_Datasets_CKAN.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/87ac73e9-3115-4ce0-8d92-fc9e4baa2b97)

**Comment by tdipisa** [comment]
@abulojoshua1 @etj 
I've tested in DEV (http://faoclh.geo-solutions.it/) this feature and in my opinion there is a wrong behavior:

- I open the dataset search page
- I expand a facet (i.e. **Type of Resource** but it is the same for the other) and then I click on one item

Expected result
The dataset list is properly filtered and all facets I've expanded are still expanded

Current result
The dataset list is properly filtered but all facets I've expanded are now collapsed

**Comment by abulojoshua1** [comment]
> @abulojoshua1 @etj
> I've tested in DEV (http://faoclh.geo-solutions.it/) this feature and in my opinion there is a wrong behavior:
> 
> * I open the dataset search page
> * I expand a facet (i.e. **Type of Resource** but it is the same for the other) and then I click on one item
> 
> Expected result
> The dataset list is properly filtered and all facets I've expanded are still expanded
> 
> Current result
> The dataset list is properly filtered but all facets I've expanded are now collapsed

@tdipisa, [here](https://github.com/geosolutions-it/ckanext-faoclh/pull/62) is a PR fix for this issue.
