### ISSUE TITLE
Missing images in home

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#55]
Images are missing for some card items in home
![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/ca73149b-dfeb-42dc-b270-957732458006)

We have to find some relevant Royalty free images on the web to use for this items. Those images then need to be verisoned as usual in the related directory [here](https://github.com/geosolutions-it/ckanext-faoclh/tree/master/ckanext/faoclh/public/fao/images) ready to be used for the involved items in home.

Since vocabularies can be created/edited from the admin tool we can consider to include an image upload functionality so that the administrator can set an image for each vocabulary entry

![image](https://user-images.githubusercontent.com/1280027/83860995-53815b80-a720-11ea-970d-ede59005486b.png)

If no images are uploaded by the administrator the FAO logo must be used as default in home page:

![image](https://user-images.githubusercontent.com/1280027/83861211-9a6f5100-a720-11ea-95c6-92a6f23ae142.png)

**Comment by abulojoshua1** [comment]
@tdipisa, regarding this issue, all vocabulary custom tags do use hardcoded image source URLs and most of them do not have these images in the public directory. When a new tag is added (under geographical; focus, kind of activity, type of resource), they will have no image for them, I think it will be best if we add an image upload feature for the tags.
