### ISSUE TITLE
Localized tags Issue

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#56]
Localized tags fields should not appear and should be disabled for the FAO-CLH CKAN instance in dataset edit page

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/c4a3ea4a-48c9-49f9-8a20-b7f4b54eaf8a)

In the following case then (dataset [tools-for-modelling-efficient-agriculture-practices](http://faoclh.geo-solutions.it/dataset/tools-for-modelling-efficient-agriculture-practices)), we have also a wrong rendering of the localized tag fields: maybe an issue in ckanext-multilang or a compatibility issue with ckanext-faoclh? This need to be investigated and fixed anyway.

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/d801bdb5-4977-424b-8a5c-b3c8dfc91221)

**Comment by etj** [comment]
Once set 
```
   multilang.enable_tag_localization = False
```
the field will not show up (as required in this FAO setup).

It's anyway a bug on its own that needs investigation:
   https://github.com/geosolutions-it/ckanext-multilang/issues/28
