### ISSUE TITLE
Year of Release Resource Field

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#79]
The year of release field of resources should not be free text but a date field with format YYYY.
Now it is free text and we have problems

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/7a6c79bc-79d4-40e4-86fa-4d1cb416ffac)

In view mode of a resource the year of release value must be properly formatted (without comma):

![2020_06_24_16_01_06_Country_experience_on_GHG_inventory_Africa_Ethiopia_training_on_GHG_inventor](https://user-images.githubusercontent.com/1280027/85570875-ff3d0d80-b633-11ea-88be-a4b81ebd8c4b.png)

**Comment by abulojoshua1** [comment]
@tdipisa, just for clarity, is there a possibility, by any chance that the "year of release" of a resource is greater than the current (the current year when the user is making a new resource entry)?
