### ISSUE TITLE
Issue selecting Facet items

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#86]
There are problems while selecting items in facets: if not items are selected the facet closes.

![facet](https://user-images.githubusercontent.com/1280027/85684777-b6866280-b6ce-11ea-9dac-1f18b45aca66.gif)

**Comment by abulojoshua1** [comment]
@tdipisa, [the PR](https://github.com/geosolutions-it/ckanext-faoclh/pull/89) for issue #80 fixes the issue described here, should I go ahead and move this issue to review? I already mentioned in the description for the [PR fixing issue #80](https://github.com/geosolutions-it/ckanext-faoclh/pull/89) that it is also being solved within the PR.

**Comment by tdipisa** [comment]
@abulojoshua1, yes you should do that. Thank you.
