### ISSUE TITLE
Change "My Groups" to "My Topics"

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#92]
In the user dashboard section there is still the "My Groups" label, that should be "My Topics" for the FAO CLH extension. The i18n files need to be properly fixed for this.

![2020_06_26_13_07_55_Manage_ckanadmin_Users_CKAN.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/81a1271c-1f4e-4447-95d5-0ddafe30b458)

**Comment by abulojoshua1** [comment]
@tdipisa, should this change be applied to all the required locales (English, Spanish, Arabic, French, Chinese, Italian, Russian)?

**Comment by tdipisa** [comment]
@abulojoshua1 good question. Since the recently asked to limit the supported language for now to only EN, FR and ES, please provide only translations for these.
