### ISSUE TITLE
Enable common preview tools for resources

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#93]
It would be good to enable the most common preview tools for the preview of resources. We should at least enable the following ones (the reference CKAN online documentation [here](https://docs.ckan.org/en/2.8/maintaining/data-viewer.html)):

```
ckan.plugins = resource_proxy stats text_view image_view recline_view recline_map_view pdf_view webpage_view multilang rating ytp_comments faoclh

# Define which views should be created by default
# (plugins must be loaded in ckan.plugins)
ckan.views.default_views = image_view text_view recline_view recline_map_view pdf_view webpage_view

# Customize which text formats the text_view plugin will show
ckan.preview.json_formats = json
ckan.preview.xml_formats = xml rdf rdf+xml owl+xml atom rss
ckan.preview.text_formats = text plain text/plain

# Customize which image formats the image_view plugin will show
ckan.preview.image_formats = png jpeg jpg gif
```

The enablement of the available preview tool in ckan must be properly documented in the README file

**Comment by abulojoshua1** [comment]
@tdipisa, the datastore POST create API endpoint (`/api/3/action/datastore_create`) is not compatible with `ckanext-multilang`. When I enter map-data (latitude and longitude values needed to test` recline_view` and `recline_map_view`) in the datastore using the API endpoint, I get the error message below:
```
IntegrityError: (psycopg2.IntegrityError) null value in column "text" violates not-null constraint DETAIL: Failing row contains (85, f59bfc35-a852-4084-9297-891f632db1d0, name, en, null). [SQL: 'INSERT INTO resource_multilang (resource_id, field, lang, text) VALUES (%(resource_id)s, %(field)s, %(lang)s, %(text)s) RETURNING resource_multilang.id'] [parameters: {'lang': u'en', 'text': None, 'resource_id': u'f59bfc35-a852-4084-9297-891f632db1d0', 'field': 'name'}]
```
Should I go ahead and make a fix for it in this issue or open a new issue for to fix the above error?

**Comment by tdipisa** [comment]
@abulojoshua1, it is strange to me. Anyway, please open a separate issue for this for now and report good description of the problem there.

**Comment by abulojoshua1** [comment]
> @tdipisa, the datastore POST API endpoint (`/api/3/action/datastore_create`) is not compatible with `ckanext-multilang`. When I enter map-data (latitude and longitude values needed to test` recline_view` and `recline_map_view`) in the datastore using the API endpoint, I get the error message below:
> 
> ```
> IntegrityError: (psycopg2.IntegrityError) null value in column "text" violates not-null constraint DETAIL: Failing row contains (85, f59bfc35-a852-4084-9297-891f632db1d0, name, en, null). [SQL: 'INSERT INTO resource_multilang (resource_id, field, lang, text) VALUES (%(resource_id)s, %(field)s, %(lang)s, %(text)s) RETURNING resource_multilang.id'] [parameters: {'lang': u'en', 'text': None, 'resource_id': u'f59bfc35-a852-4084-9297-891f632db1d0', 'field': 'name'}]
> ```
> 
> Should I go ahead and make a fix for it in this issue or open a new issue for to fix the above error?

I've opened [this new issue](https://github.com/geosolutions-it/ckanext-faoclh/issues/99) to fix the error reported above.

**Comment by etj** [comment]
I created a wiki page with the very long explanation in the original PR:
   https://github.com/geosolutions-it/ckanext-faoclh/wiki/Enabling-Common-Resource-Preview-Tools
