### ISSUE TITLE
Start a search from "FAO Specific Info"

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#94]
In the FAO Specific Info make the custom vocabulaties values clickable so that the user can click on them to start a filtered search (i.e.  if I click on Policy Making, I will be able to see all policy making datasets).

![2020_06_26_14_22_33_Tools_for_modelling_efficient_agriculture_practices_Datasets_CKAN.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/98973d7e-7287-40e8-bce8-6124e9b07941)

In the example above, if I click on **Tool**, the dataset search page opens with the **Tool** item selected in facet:

![image](https://user-images.githubusercontent.com/1280027/85859857-1dcf1000-b7be-11ea-9c95-900da47ff1a4.png)

**Comment by tdipisa** [comment]
@abulojoshua1 can you please provide am estimate for this issue as required?

**Comment by abulojoshua1** [comment]
@tdipisa, just before I provide an estimate, will the filtered search take place on the [dataset search page](http://faoclh.geo-solutions.it/dataset)?

**Comment by tdipisa** [comment]
@abulojoshua1 As I already mentioned in Skype some day ago, I've updated the description. did you look at it? The description contains the answer. Please give me an estimate of the effort, there is an Estimate selector above in the issue.
